<a href="https://colab.research.google.com/github/Williamsjanthony15/spaceX_launch/blob/main/spaceXLaunches.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Dependencies

In [1]:
import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, LogisticRegression

Import CSV File

In [2]:
from google.colab import files
upload = files.upload()

Saving database.csv to database (2).csv

Assigning DF to the CSV File

In [30]:
df = pd.read_csv('./database.csv')
df

   Flight Number        Launch Date  ... Landing Type Landing Outcome
0           F1-1      24 March 2006  ...          NaN             NaN
1           F1-2      21 March 2007  ...          NaN             NaN
2           F1-3      3 August 2008  ...          NaN             NaN
3           F1-3      3 August 2008  ...          NaN             NaN
4           F1-3      3 August 2008  ...          NaN             NaN
5           F1-4  28 September 2008  ...          NaN             NaN
6           F1-5       14 July 2009  ...          NaN             NaN
7           F9-1        4 June 2010  ...    Parachute         Failure
8           F9-2    8 December 2010  ...    Parachute         Failure
9           F9-3        22 May 2012  ...          NaN             NaN
10          F9-4     8 October 2012  ...          NaN             NaN
11          F9-4     8 October 2012  ...          NaN             NaN
12          F9-5       1 March 2013  ...          NaN             NaN
13          F9-6  29 September 2013  ...        Ocean         Failure
14          F9-7    3 December 2013  ...         None             NaN
15          F9-8    6 December 2014  ...         None             NaN
16          F9-9      18 April 2014  ...        Ocean         Success
17         F9-10       14 July 2014  ...        Ocean         Success
18         F9-11      5 August 2014  ...         None             NaN
19         F9-12   7 September 2014  ...         None             NaN
20         F9-13  21 September 2014  ...        Ocean         Success
21         F9-14    10 January 2015  ...         Ship         Failure
22         F9-15   11 February 2015  ...        Ocean         Success
23         F9-16       2 March 2015  ...         None             NaN
24         F9-16       2 March 2015  ...         None             NaN
25         F9-17      14 April 2015  ...         Ship         Failure
26         F9-18      27 April 2015  ...         None             NaN
27         F9-19       28 June 2015  ...          NaN             NaN
28          FT-1   22 December 2015  ...         Land         Success
29         F9-21    17 January 2016  ...         Ship         Failure
30          FT-2       4 March 2016  ...         Ship         Failure
31          FT-3       8 April 2016  ...         Ship         Success
32          FT-4         6 May 2016  ...         Ship         Success
33          FT-5        27 May 2016  ...         Ship         Success
34          FT-6       15 June 2016  ...         Ship         Failure
35          FT-6       15 June 2016  ...         Ship         Failure
36          FT-7       18 July 2016  ...         Land         Success
37          FT-8     14 August 2016  ...         Ship         Success
38          FT-9   1 September 2016  ...          NaN             NaN
39         FT-10    14 January 2017  ...         Ship         Success
40         FT-11   19 February 2017  ...         Land         Success

[41 rows x 16 columns]

Show first 5 rows of DF

In [ ]:
df.head(5)

Show the description and the info of the data set.

In [ ]:
df.columns

In [ ]:
df.info

Ensure that any date columns have been cast into a datetime object in your DataFrame.

In [39]:
df = df.drop(index=0)
df['Launch Date'] = pd.to_datetime(df['Launch Date']).sort_values(ascending=False).head(40)
date = df[['Launch Date', 'Launch Time']]

date

   Launch Date Launch Time
1   2007-03-21       01:10
2   2008-08-03       03:34
3   2008-08-03       03:34
4   2008-08-03       03:34
5   2008-09-28       23:15
6   2009-07-14       03:35
7   2010-06-04       18:45
8   2010-12-08       15:43
9   2012-05-22       07:44
10  2012-10-08       00:35
11  2012-10-08       00:35
12  2013-03-01       15:10
13  2013-09-29       16:00
14  2013-12-03       22:41
15  2014-12-06       22:06
16  2014-04-18       19:25
17  2014-07-14       15:15
18  2014-08-05       08:00
19  2014-09-07       05:00
20  2014-09-21       05:52
21  2015-01-10       09:47
22  2015-02-11       23:03
23  2015-03-02       03:50
24  2015-03-02       03:50
25  2015-04-14       20:10
26  2015-04-27       23:03
27  2015-06-28       14:21
28  2015-12-22       01:29
29  2016-01-17       18:42
30  2016-03-04       23:35
31  2016-04-08       20:43
32  2016-05-06       05:21
33  2016-05-27       21:39
34  2016-06-15       14:29
35  2016-06-15       14:29
36  2016-07-18       04:45
37  2016-08-14       05:26
38  2016-09-01       13:07
39  2017-01-14       17:54
40  2017-02-19       14:39

In [ ]:
time = pd.to_datetime(df['Launch Time'].sort_values(ascending=False)).head(50)
time

Using a regression model, split your data into train and test data

In [ ]:
stringified = {'Success': True, 'Failure': False}
new_results = df['Mission Outcome'].map(stringified)
new_results

In [84]:
# exception = str.replace('NaN', 'None', '-1')
X = df['Mission Outcome'].map(stringified).values
# y = df['Payload Type'].replace(NaN, 'None').values
y = df['Payload Type'].fillna('None').values

# lr = LogisticRegression
# lr.fit(X, y)
X = X.reshape(-1, 1)
y = y.reshape(-1, 1)
# NaN_exception = df['Payload Type'].apply(lambda y: ('NaN','Unknown'))
y

array([['Research Satellite'],
       ['None'],
       ['Communication Satellite'],
       ['Research Satellites'],
       ['Human Remains'],
       ['None'],
       ['Weather Satellite'],
       ['None'],
       ['Space Station Supplies'],
       ['Space Station Supplies'],
       ['Space Station Supplies'],
       ['Communication Satellite'],
       ['Space Station Supplies'],
       ['Communication/Research Satellite'],
       ['Communication Satellite'],
       ['Communication Satellite'],
       ['Space Station Supplies'],
       ['Communication Satellite'],
       ['Communication Satellite'],
       ['Communication Satellite'],
       ['Space Station Supplies'],
       ['Space Station Supplies'],
       ['Weather Satellite'],
       ['Communication Satellite'],
       ['Communication Satellite'],
       ['Space Station Supplies'],
       ['Communication Satellite'],
       ['Space Station Supplies'],
       ['Communication Satellite'],
       ['Weather Satellite'],
       ['Communication Satellite'],
       ['Space Station Supplies'],
       ['Communication Satellite'],
       ['Communication Satellite'],
       ['Communication Satellite'],
       ['Communication Satellite'],
       ['Space Station Supplies'],
       ['Communication Satellite'],
       ['Communication Satellite'],
       ['Communication Satellite'],
       ['Space Station Supplies']], dtype=object)

In [ ]:
model = LinearRegression()
model.fit(X, y)

Fit your training split to the regression model.

Show your regression model’s score.

Draw at least three conclusions from your regression model.

In [ ]:
print('SpaceX is not only Utilizing Government and personal funded aircraft to ship into space, but they are utilizing other countries, Which allow other countries to send into space as well')
print('More Failures than success\' Shows us that some times you need to fail before you can succeed')
print('Even those in the highest intellectual positions, can fail.')